## modified from https://github.com/zabbix/zabbix-docker/blob/4.4/kubernetes.yaml
kind: Service
apiVersion: v1
metadata:
  name: zabbix-server
  labels:
    app: zabbix
  namespace: zabbix
spec:
  type: NodePort
  ports:
  - port: 10051
    nodePort: 30051
    protocol: TCP
    targetPort: 10051
    name: zabbix-trapper
  - port: 162
    targetPort: 1162
    protocol: UDP
    name: snmp-trap
  selector:
    app: zabbix
  #externalIPs:
  #- <Specify external IP here>
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zabbix-server
  labels:
    app: zabbix
    tier: server
  namespace: zabbix
spec:
  replicas: 1
  matchLabels:
    app: zabbix
    tier: server
  template:
    metadata:
      labels:
        name: zabbix-server
        app: zabbix
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-mysql
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 10051
            protocol: TCP
            name: zabbix-trapper
          readinessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: zabbix-trapper
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
          - name: MYSQL_USER
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-user
          - name: MYSQL_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-zbx-pass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
              name: db-secret
              key: db-root-pass
          - name: MYSQL_DATABASE
            value: "zabbix"
          - name: ZBX_JAVAGATEWAY_ENABLE
            value: "true"
          - name: ZBX_STARTJAVAPOLLERS
            value: "5"
          - name: ZBX_ENABLE_SNMP_TRAPS
            value: "true"
          - name: ZBX_STARTPROXYPOLLERS
            value: "5"
          - name: ZBX_PROXYCONFIGFREQUENCY
            value: "60"
          volumeMounts:
          - name: zabbix-db-storage
            mountPath: /var/lib/zabbix/snmptraps/
            readOnly: true
        - name: zabbix-snmptraps
          image: zabbix/zabbix-snmptraps
          imagePullPolicy: Always
          ports:
          - containerPort: 1162
            protocol: UDP
            name: snmp-trap
          volumeMounts:
          - name: zabbix-db-storage
            mountPath: /var/lib/zabbix/snmptraps/
            readOnly: false
        -name: zabbix-agent
          image: zabbix/zabbix-agent
          imagePullPolicy: Always
          ports:
          - containerPort: 10050
            name: zabbix-agent
          env:
          - name: ZBX_HOSTNAME
            value: "Zabbix Agent"
          - name: ZBX_SERVER_HOST
            value: "zabbix-server"
          - name: ZBX_PASSIVE_ALLOW
            value: "true"
          - name: ZBX_STARTAGENTS
            value: "3"
          - name: ZBX_TIMEOUT
            value: "10"
          securityContext:
            privileged: true
      volumes:
       - hostPath:
          path: /zabbix/
         name: zabbix-db-storage
